"""Hand-written type stub for kp (Kompute) 0.9.0 — the Vulkan/Kompute Python bindings.

kp is a pybind11 C-extension with no py.typed marker and no upstream type
stubs. This stub covers only the API surface used by the Vulkan solver
(``swe_gpu*.py``) — Manager, Tensor, Sequence, Algorithm, and the Op*
classes recorded onto a Sequence. Extend on demand as new kp API usage is
added; do not front-load the full binding surface.

Source of truth: kp 0.9.0's pybind11 binding definitions
(https://github.com/KomputeProject/kompute/blob/v0.9.0/python/src/main.cpp),
which is the canonical spec for argument names/types/defaults — read directly
from the ``py::class_``/``.def(...)`` calls, not from prose docs (kp's Python
docs on kompute.cc lag the actual binding signatures in places).
"""

from collections.abc import Sequence as _Sequence
from typing import overload

import numpy as np
from numpy.typing import NDArray

class TensorTypes:
    device: TensorTypes
    host: TensorTypes
    storage: TensorTypes

class OpBase: ...

class OpTensorSyncDevice(OpBase):
    def __init__(self, tensors: _Sequence[Tensor]) -> None: ...

class OpTensorSyncLocal(OpBase):
    def __init__(self, tensors: _Sequence[Tensor]) -> None: ...

class OpTensorCopy(OpBase):
    def __init__(self, tensors: _Sequence[Tensor]) -> None: ...

class OpAlgoDispatch(OpBase):
    @overload
    def __init__(self, algorithm: Algorithm, push_consts: _Sequence[float] = ...) -> None: ...
    @overload
    def __init__(self, algorithm: Algorithm, push_consts: NDArray[np.generic]) -> None: ...

class OpMult(OpBase):
    def __init__(self, tensors: _Sequence[Tensor], algorithm: Algorithm) -> None: ...

class Algorithm:
    def get_tensors(self) -> list[Tensor]: ...
    def destroy(self) -> None: ...
    def is_init(self) -> bool: ...

class Tensor:
    def data(self) -> NDArray[np.generic]: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def tensor_type(self) -> TensorTypes: ...
    def data_type(self) -> int: ...
    def is_init(self) -> bool: ...
    def destroy(self) -> None: ...

class Sequence:
    def record(self, op: OpBase) -> Sequence: ...
    @overload
    def eval(self) -> Sequence: ...
    @overload
    def eval(self, op: OpBase) -> Sequence: ...
    @overload
    def eval_async(self) -> Sequence: ...
    @overload
    def eval_async(self, op: OpBase) -> Sequence: ...
    @overload
    def eval_await(self) -> Sequence: ...
    @overload
    def eval_await(self, wait: int) -> Sequence: ...
    def is_recording(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_init(self) -> bool: ...
    def clear(self) -> Sequence: ...
    def rerecord(self) -> Sequence: ...
    def get_timestamps(self) -> list[int]: ...
    def destroy(self) -> None: ...

class Manager:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, device: int) -> None: ...
    @overload
    def __init__(
        self,
        device: int = ...,
        family_queue_indices: _Sequence[int] = ...,
        desired_extensions: _Sequence[str] = ...,
    ) -> None: ...
    def destroy(self) -> None: ...
    def sequence(self, queue_index: int = ..., total_timestamps: int = ...) -> Sequence: ...
    def tensor(self, data: NDArray[np.float32], tensor_type: TensorTypes = ...) -> Tensor: ...
    def tensor_t(self, data: NDArray[np.generic], tensor_type: TensorTypes = ...) -> Tensor: ...
    def algorithm(
        self,
        tensors: _Sequence[Tensor],
        spirv: bytes,
        workgroup: tuple[int, int, int] = ...,
        spec_consts: _Sequence[float] | NDArray[np.generic] = ...,
        push_consts: _Sequence[float] | NDArray[np.generic] = ...,
    ) -> Algorithm: ...
    def list_devices(self) -> list[dict[str, object]]: ...
    def get_device_properties(self) -> dict[str, object]: ...

__version__: str
